packages:
  - name: twillio
    actions:
      - name: getText
        limits:
          timeout: 120000
          memory: 512
        runtime: 'go:1.17'
environment:
  ACCOUNT_SID: ${ACCOUNT_SID}
  AUTH_TOKEN: ${AUTH_TOKEN}
  TO_PHONE: ${TO_PHONE}
  FROM_PHONE: ${FROM_PHONE}
